name: nexsoil
description: "NexSoil Rover Controller App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bluetooth_serial: ^0.4.0
  shared_preferences: ^2.3.2
  google_fonts: ^6.2.1
  fl_chart: ^0.69.0
  provider: ^6.1.2
  permission_handler: ^12.0.1
  http: ^1.2.0
  network_info_plus: ^6.0.1
  web_socket_channel: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
